name: i_am_health
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  
flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#b2b4b9"
  image_path_ios: "images/launcher/iconios.png"
  image_path_android: "images/launcher/iconand.png"


flutter:
  uses-material-design: true
  assets:
   - images/

module:
  androidX: true